CREATE TABLE `teste-atividades`.`atividades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(600) NOT NULL,
  `dt_inicio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_fim` DATETIME NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `situacao` TINYINT NOT NULL DEFAULT 1,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`));
